import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme/theme-provider"
import { Toaster } from "@/components/ui/toaster"

import "./globals.css";

import Navbar from "@/components/layout/navbar/navbar";
import { cookies } from "next/headers";

const outfit = localFont({
  src: "./fonts/Outfit.ttf",
  variable: "--font-outfit",
  weight: "100 900",
});

const data = cookies().get('authToken')
const userString = cookies().get('user')
const token = data?.value
const userData: string | undefined = userString?.value

const user = userData ? JSON.parse(userData) : ''

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    <html lang="en" className="dark">
      <body
        className={`${outfit.className} antialiased flex justify-center items-center overflow-x-hidden`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <section className="max-w-screen-xl">
            <Navbar user={user} token={token ? token : ''}/>
            {children}
            <Toaster />
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
